pipeline:
  name: todo-app
  identifier: todoapp
  projectIdentifier: Marcos
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Test and Build
        identifier: Test_and_Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Test
                  identifier: Test
                  spec:
                    connectorRef: marcosoliveirateixeira
                    image: node:16
                    shell: Sh
                    command: |-
                      npm install
                      npm test
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Push
                  identifier: Push
                  spec:
                    connectorRef: marcosoliveirateixeira
                    repo: marcosoliveirateixeira/jorgin
                    tags:
                      - latest
                  failureStrategies: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
    - stage:
        name: Deploy dessa porra
        identifier: Deploy_dessa_porra
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: todoService
          environment:
            environmentRef: todoEnv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: todoInfra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  properties:
    ci:
      codebase:
        connectorRef: Marcos
        repoName: todo-app
        build: <+input>
